name: Deploy to EC2

on:
  push:
    branches:
      - main  # You can specify the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up SSH for EC2
      - name: Set up SSH key for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Your private key stored as a secret

      # Install dependencies (Optional if needed, e.g., if you need specific SSH tools)
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      # Deploy the application to EC2
      - name: Deploy to EC2
        run: |
          # SSH into the EC2 instance and perform deployment
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd Test  # Navigate to the directory where your app is located
            git pull origin main  # Pull the latest code from GitHub
            npm install  # Install dependencies
            pm2 restart test || pm2 start index.js --name my-node-app  # Restart or start the app with pm2
            pm2 save  # Save the pm2 process list
          EOF
